### ISSUE TITLE
kernel patch missing clock-frequency property

### ISSUE THREAD

**Issue by RomSand** [jhswartz/rk3229#5]
I'm using kernel also on Ubuntu 18.04 during the load I get errors regarding the CPU would like to ask if it's critical. Thank you.
 `Jan 28 10:58:20 MXQBionic kernel: CPU: Testing write buffer coherency: ok
Jan 28 10:58:20 MXQBionic kernel: /cpus/cpu@f00 missing clock-frequency property
Jan 28 10:58:20 MXQBionic kernel: /cpus/cpu@f01 missing clock-frequency property
Jan 28 10:58:20 MXQBionic kernel: /cpus/cpu@f02 missing clock-frequency property
Jan 28 10:58:20 MXQBionic kernel: /cpus/cpu@f03 missing clock-frequency property
Jan 28 10:58:20 MXQBionic kernel: CPU0: thread -1, cpu 0, socket 15, mpidr 80000f00
Jan 28 10:58:20 MXQBionic kernel: Setting up static identity map for 0x60100000 - 0x60100060
Jan 28 10:58:20 MXQBionic kernel: rcu: Hierarchical SRCU implementation.
Jan 28 10:58:20 MXQBionic kernel: smp: Bringing up secondary CPUs ...
Jan 28 10:58:20 MXQBionic kernel: CPU1: thread -1, cpu 1, socket 15, mpidr 80000f01
Jan 28 10:58:20 MXQBionic kernel: CPU2: thread -1, cpu 2, socket 15, mpidr 80000f02
Jan 28 10:58:20 MXQBionic kernel: CPU3: thread -1, cpu 3, socket 15, mpidr 80000f03
Jan 28 10:58:20 MXQBionic kernel: smp: Brought up 1 node, 4 CPUs
Jan 28 10:58:20 MXQBionic kernel: SMP: Total of 4 processors activated (192.00 BogoMIPS).
Jan 28 10:58:20 MXQBionic kernel: CPU: All CPU(s) started in SVC mode.
`
And also tis:
`
Jan 28 10:58:21 MXQBionic kernel: handlers:
Jan 28 10:58:21 MXQBionic kernel: [<3bee900b>] dw_hdmi_hardirq threaded [<ab950436>] dw_hdmi_irq
Jan 28 10:58:21 MXQBionic kernel: [<5226ee1b>] dw_hdmi_cec_hardirq threaded [<b5eccaf4>] dw_hdmi_cec_thread
Jan 28 10:58:21 MXQBionic kernel: Disabling IRQ #35
`
Thanks

**Comment by jhswartz** [comment]
These messages aren't critical.

With regard to "missing clock-frequency", I had initially included nodes to get rid of this message - but take a look at the response I received once I had submitted the patch: https://patchwork.kernel.org/patch/10997647/

> > +&cpu0 {
> > +	clock-frequency = <1464000000>;
>
> not sure I understand the reasoning here.
> There seems to be a regulator defined, so the cpu cores should
> have operating points defined to allow them to switch between
> different frequencies as needed.

So to get the patch accepted, I removed these nodes and resubmitted. See: https://patchwork.kernel.org/patch/11089199/

The unhandled IRQ error message regarding HDMI CEC isn't anything to worry about, and without a copy of the Technical Reference Manual for the RK3229 I don't have the motivation to fix it.

**Comment by jhswartz** [comment]
Would you mind telling me about your set up and configuration? I'm curious to hear about how others have used this info. Thanks.

**Comment by RomSand** [comment]
My box is MXQ-4k have couple of this one, Linux is installed on internal storage tried devuan but I'm more used to ubuntu same thing only userized ) want to use for home automation now trying to install home assistant but having some problems cause of missing kernel modules grpc and aufs will try to recompile kernel with them.  can let you know if it worked or not. Was also thinking if it's possible to use android kernel in linux and how did hey get HW video acceleration on Radxa Rock 2 almost same cpu.

**Comment by RomSand** [comment]
I build in aufs ito kernel but still receiving error ="AUFS was not found in /proc/filesystems" storage-driver=aufs so docker can't start... did you try to kompile kernel with AUFS ?

**Comment by jhswartz** [comment]
I don't use AUFS, and in most cases I don't need filesystem overlays. But the kernel already has OverlayFS included in mainline - while AUFS was rejected for mainline inclusion, and to use it you are required to build it as an external kernel module. Why do you need it?

I also have no use for grpc, and I've never heard of it, to be honest. Are you trying to build a kernel for software usually used in an Android environment?

And yes, you can use an android kernel with a GNU userland, but there are a few hoops you have to jump through to make it work coherently. One example of this is that you will have to add users to a certain group to allow network access. I wouldn't advocate it because I don't use that kind of setup personally, but it might work well enough for you.

In terms of hardware video acceleration - the Radxa Rock 2 is built around an RK3288 SoC, which is quite different from RK3229, especially as the GPU core of the RK3288 is an ARM Mali-T760 but the RK3229 has an ARM Mali-400.

In terms of mainline kernel usage, the RK3288 requires the panfrost driver, and the RK3229 requires the lima driver - and your userland will require mesa and drm to be built with support for the correct driver's API.

Last time I tried building mesa and drm with lima support, I didn't get any luck with accelerated X or Wayland. If I have better luck in future, then I will document the process here.

**Comment by RomSand** [comment]
Hi, Thanks for detailed responce, aufs I need to be able to run docker (and Home Assistant under it).
grpc is also in it's requirement don't know if it's mandatory.
There is kernel 4.10 from Android that's working really good with all drivers and it has HW acceleration support was thinking to play with it.
I build mesa and drm for gma500 and agree that it wasn't so pleasant...

**Comment by RomSand** [comment]
Did you tried docker on this boards and also I know that there is android9 for rk3229 did you try it ?

**Comment by jhswartz** [comment]
No, I have not tried Docker - no interest in it on any platform.
Also, no interest in running Android if I can run GNU/Linux.

Likewise, no interest in running Linux + distributions containing proprietary blobs and patches with no intention of being upstreamed/mainlined.

But sometimes running any of these is a necessary starting point to get things to work. :)
